version: '3.4'
services:
  service-registry:
    build: .
    image: registry.idler.com/service-gateway
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
