#server:
#  port: 8082
spring:
  application:
    name: zipkin-client
  zipkin:
    base-url: http://192.168.225.5:9411
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
logging:
  pattern:
    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
  level:
    org:
      springframework:
        web: DEBUG

